services:
  youtube-sentiment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-sentiment-api
    ports:
      - "6889:6889"
    environment:
      # AWS Credentials for MLflow S3 access
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # MLflow tracking URI
      - MLFLOW_TRACKING_URI=http://3.29.129.159:5000/
    volumes:
      # Mount model files (optional - if you want to update models without rebuilding)
      - ./lgbm_model.pkl:/app/lgbm_model.pkl
      - ./tfidf_vectorizer.pkl:/app/tfidf_vectorizer.pkl
      # Mount logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6889/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


